import 'dart:io';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/election.dart';

class PdfGenerator {
  static const _navy = PdfColor.fromInt(0xFF14213D);
  static const _orange = PdfColor.fromInt(0xFFFCA311);
  static const _green = PdfColor.fromInt(0xFF2ECC71);
  static const _gray = PdfColor.fromInt(0xFFF5F5F5);
  static const _border = PdfColor.fromInt(0xFFE5E7EB);
  static const _textSecondary = PdfColor.fromInt(0xFF6B7280);
  static const _whiteTranslucent = PdfColor.fromInt(0x33FFFFFF); // ~20% white
  static const _whiteDim = PdfColor.fromInt(0xB3FFFFFF);         // ~70% white

  static Future<void> exportElectionResults({
    required Election election,
    required ElectionResults results,
  }) async {
    final pdf = pw.Document();

    final sortedResults = List<CandidateResult>.from(results.results)
      ..sort((a, b) => b.votes.compareTo(a.votes));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (_) => _buildHeader(election),
        footer: (ctx) => _buildFooter(ctx),
        build: (ctx) => [
          pw.SizedBox(height: 20),
          _buildSummarySection(election, results),
          pw.SizedBox(height: 24),
          if (results.winner != null) ...[
            _buildWinnerSection(results.winner!, results.totalVotes),
            pw.SizedBox(height: 24),
          ],
          _buildResultsTable(sortedResults, results.totalVotes),
          pw.SizedBox(height: 24),
          _buildTurnoutSection(results),
        ],
      ),
    );

    final bytes = await pdf.save();
    final dir = await getTemporaryDirectory();
    final fileName = 'results_${election.title.replaceAll(RegExp(r'[^\w]'), '_')}.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(bytes);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: 'Election Results — ${election.title}',
    );
  }

  // ── Header ────────────────────────────────────────────────────────────────

  static pw.Widget _buildHeader(Election election) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: _orange, width: 2)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Text('ELECTROX',
                style: pw.TextStyle(
                    fontSize: 20, fontWeight: pw.FontWeight.bold, color: _navy)),
            pw.Text('Digital Voting Platform',
                style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
          ]),
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
            pw.Text('Election Results Report',
                style: pw.TextStyle(
                    fontSize: 13, fontWeight: pw.FontWeight.bold, color: _navy)),
            pw.Text(_formatDate(DateTime.now()),
                style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
          ]),
        ],
      ),
    );
  }

  // ── Footer ────────────────────────────────────────────────────────────────

  static pw.Widget _buildFooter(pw.Context ctx) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: _gray, width: 1)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Electrox',
              style: pw.TextStyle(fontSize: 9, color: _textSecondary)),
          pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: pw.TextStyle(fontSize: 9, color: _textSecondary)),
        ],
      ),
    );
  }

  // ── Summary ───────────────────────────────────────────────────────────────

  static pw.Widget _buildSummarySection(Election election, ElectionResults results) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Container(
        width: double.infinity,
        padding: const pw.EdgeInsets.all(16),
        decoration: pw.BoxDecoration(
          color: _navy,
          borderRadius: pw.BorderRadius.circular(8),
        ),
        child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text(election.title,
              style: pw.TextStyle(
                  fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
          pw.SizedBox(height: 4),
          pw.Text(election.description,
              style: pw.TextStyle(fontSize: 11, color: _whiteDim)),
          pw.SizedBox(height: 12),
          pw.Row(children: [
            _summaryChip('Status', election.statusDisplay.toUpperCase()),
            pw.SizedBox(width: 12),
            _summaryChip('Organizer', election.organizerEmail),
          ]),
        ]),
      ),
      pw.SizedBox(height: 16),
      pw.Row(children: [
        pw.Expanded(child: _statBox('Total Votes', '${results.totalVotes}', _navy)),
        pw.SizedBox(width: 12),
        pw.Expanded(child: _statBox('Total Voters', '${election.voters.length}', _navy)),
        pw.SizedBox(width: 12),
        pw.Expanded(child: _statBox('Turnout', '${results.turnoutPercentage.toStringAsFixed(1)}%', _green)),
        pw.SizedBox(width: 12),
        pw.Expanded(child: _statBox('Candidates', '${election.candidates.length}', _orange)),
      ]),
      pw.SizedBox(height: 8),
      pw.Row(children: [
        _infoRow('Start', _formatDate(election.startDate)),
        pw.SizedBox(width: 24),
        _infoRow('End', _formatDate(election.endDate)),
        pw.SizedBox(width: 24),
        _infoRow('Visibility', election.resultVisibility),
      ]),
    ]);
  }

  static pw.Widget _summaryChip(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: pw.BoxDecoration(
        color: _whiteTranslucent,
        borderRadius: pw.BorderRadius.circular(20),
      ),
      child: pw.RichText(
        text: pw.TextSpan(children: [
          pw.TextSpan(
              text: '$label: ',
              style: pw.TextStyle(fontSize: 9, color: _whiteDim)),
          pw.TextSpan(
              text: value,
              style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.white)),
        ]),
      ),
    );
  }

  static pw.Widget _statBox(String label, String value, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: _gray,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: color, width: 0.5),
      ),
      child: pw.Column(children: [
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 20, fontWeight: pw.FontWeight.bold, color: color)),
        pw.SizedBox(height: 2),
        pw.Text(label, style: pw.TextStyle(fontSize: 9, color: _textSecondary)),
      ]),
    );
  }

  static pw.Widget _infoRow(String label, String value) {
    return pw.RichText(
      text: pw.TextSpan(children: [
        pw.TextSpan(
            text: '$label: ',
            style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
        pw.TextSpan(
            text: value,
            style: pw.TextStyle(
                fontSize: 10, fontWeight: pw.FontWeight.bold, color: _navy)),
      ]),
    );
  }

  // ── Winner ────────────────────────────────────────────────────────────────

  static pw.Widget _buildWinnerSection(CandidateResult winner, int totalVotes) {
    final pct = winner.getPercentage(totalVotes);
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: const PdfColor.fromInt(0xFFFFFBEB),
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: _orange, width: 1.5),
      ),
      child: pw.Row(children: [
        pw.Container(
          width: 48,
          height: 48,
          decoration: pw.BoxDecoration(
            color: _orange,
            borderRadius: pw.BorderRadius.circular(24),
          ),
          child: pw.Center(
            child: pw.Text('1st',
                style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white)),
          ),
        ),
        pw.SizedBox(width: 16),
        pw.Expanded(
            child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
              pw.Text('WINNER',
                  style: pw.TextStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                      color: _orange)),
              pw.Text(winner.name,
                  style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold,
                      color: _navy)),
              pw.Text(winner.email,
                  style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
            ])),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Text('${winner.votes}',
              style: pw.TextStyle(
                  fontSize: 28, fontWeight: pw.FontWeight.bold, color: _orange)),
          pw.Text('votes',
              style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
          pw.Text('${pct.toStringAsFixed(1)}%',
              style: pw.TextStyle(
                  fontSize: 13, fontWeight: pw.FontWeight.bold, color: _navy)),
        ]),
      ]),
    );
  }

  // ── Results Table ─────────────────────────────────────────────────────────

  static pw.Widget _buildResultsTable(
      List<CandidateResult> results, int totalVotes) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Text('Detailed Results',
          style: pw.TextStyle(
              fontSize: 14, fontWeight: pw.FontWeight.bold, color: _navy)),
      pw.SizedBox(height: 10),
      pw.Table(
        border: pw.TableBorder.all(color: _border, width: 0.5),
        columnWidths: {
          0: const pw.FixedColumnWidth(36),
          1: const pw.FlexColumnWidth(2.5),
          2: const pw.FlexColumnWidth(3),
          3: const pw.FixedColumnWidth(60),
          4: const pw.FixedColumnWidth(70),
        },
        children: [
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: _navy),
            children: [
              _tableHeader('Rank'),
              _tableHeader('Name'),
              _tableHeader('Email'),
              _tableHeader('Votes'),
              _tableHeader('Share'),
            ],
          ),
          ...results.asMap().entries.map((entry) {
            final i = entry.key;
            final r = entry.value;
            final pct = r.getPercentage(totalVotes);
            final isWinner = i == 0;
            final bg = isWinner
                ? const PdfColor.fromInt(0xFFFFFBEB)
                : i.isEven
                    ? PdfColors.white
                    : _gray;

            return pw.TableRow(
              decoration: pw.BoxDecoration(color: bg),
              children: [
                _tableCell('${i + 1}',
                    center: true,
                    bold: isWinner,
                    color: isWinner ? _orange : _navy),
                _tableCell(r.name,
                    bold: isWinner, color: isWinner ? _orange : _navy),
                _tableCell(r.email, small: true),
                _tableCell('${r.votes}',
                    center: true,
                    bold: isWinner,
                    color: isWinner ? _orange : _navy),
                _tableCellWithBar(pct, isWinner),
              ],
            );
          }),
        ],
      ),
    ]);
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      child: pw.Text(text,
          style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white)),
    );
  }

  static pw.Widget _tableCell(String text,
      {bool center = false,
      bool bold = false,
      bool small = false,
      PdfColor? color}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      child: pw.Text(text,
          textAlign: center ? pw.TextAlign.center : pw.TextAlign.left,
          style: pw.TextStyle(
              fontSize: small ? 8 : 10,
              fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: color ?? _navy)),
    );
  }

  static pw.Widget _tableCellWithBar(double pct, bool isWinner) {
    final barColor = isWinner ? _orange : _navy;
    final clampedPct = pct.clamp(0.0, 100.0);
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 8),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('${clampedPct.toStringAsFixed(1)}%',
              style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight:
                      isWinner ? pw.FontWeight.bold : pw.FontWeight.normal,
                  color: barColor)),
          pw.SizedBox(height: 3),
          _progressBar(clampedPct, 4, barColor),
        ],
      ),
    );
  }

  // ── Turnout ───────────────────────────────────────────────────────────────

  static pw.Widget _buildTurnoutSection(ElectionResults results) {
    final pct = results.turnoutPercentage.clamp(0.0, 100.0);
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _gray,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text('Voter Turnout',
            style: pw.TextStyle(
                fontSize: 12, fontWeight: pw.FontWeight.bold, color: _navy)),
        pw.SizedBox(height: 10),
        pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                  '${results.totalVotes} of ${results.totalVoters} voters participated',
                  style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
              pw.Text('${pct.toStringAsFixed(1)}%',
                  style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: _green)),
            ]),
        pw.SizedBox(height: 6),
        _progressBar(pct, 8, _green),
      ]),
    );
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  /// Draws a progress bar using flex-based Row — no LayoutBuilder needed.
  static pw.Widget _progressBar(double pct, double height, PdfColor color) {
    final fill = pct.clamp(0.0, 100.0);
    final empty = 100.0 - fill;
    final radius = height / 2;
    return pw.ClipRRect(
      horizontalRadius: radius,
      verticalRadius: radius,
      child: pw.Row(children: [
        if (fill > 0)
          pw.Expanded(
            flex: fill.round(),
            child: pw.Container(
              height: height,
              color: color,
            ),
          ),
        if (empty > 0)
          pw.Expanded(
            flex: empty.round(),
            child: pw.Container(
              height: height,
              color: _border,
            ),
          ),
      ]),
    );
  }

  static String _formatDate(DateTime d) {
    const months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ];
    return '${months[d.month - 1]} ${d.day}, ${d.year}';
  }
}
